[2023-01-23 11:12:03,833] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.insert_district_daily manual__2023-01-23T08:21:42.844872+00:00 [queued]>
[2023-01-23 11:12:03,842] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.insert_district_daily manual__2023-01-23T08:21:42.844872+00:00 [queued]>
[2023-01-23 11:12:03,843] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-23 11:12:03,844] {taskinstance.py:1357} INFO - Starting attempt 20 of 20
[2023-01-23 11:12:03,844] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-23 11:12:03,863] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_district_daily> on 2023-01-23 08:21:42.844872+00:00
[2023-01-23 11:12:03,871] {standard_task_runner.py:52} INFO - Started process 6395 to run task
[2023-01-23 11:12:03,875] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_final_project', 'insert_district_daily', 'manual__2023-01-23T08:21:42.844872+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/d_1_final_project.py', '--cfg-path', '/tmp/tmpm1w95joe', '--error-file', '/tmp/tmpjth1sq4f']
[2023-01-23 11:12:03,876] {standard_task_runner.py:80} INFO - Job 97: Subtask insert_district_daily
[2023-01-23 11:12:03,963] {task_command.py:369} INFO - Running <TaskInstance: d_1_final_project.insert_district_daily manual__2023-01-23T08:21:42.844872+00:00 [running]> on host da01296d3c51
[2023-01-23 11:12:04,057] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_final_project
AIRFLOW_CTX_TASK_ID=insert_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T08:21:42.844872+00:00
AIRFLOW_CTX_TRY_NUMBER=20
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T08:21:42.844872+00:00
[2023-01-23 11:12:04,243] {logging_mixin.py:115} INFO - GET DATA FROM SQL SUCCESS
[2023-01-23 11:12:04,281] {logging_mixin.py:115} INFO - GET DATA FROM SQL SUCCESS
[2023-01-23 11:12:04,418] {logging_mixin.py:115} INFO - INSERTED TO POSTGRES SUCCESSFULLY
[2023-01-23 11:12:04,455] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/d_1_final_project.py", line 112, in fun_insert_district_daily
    transformer.create_district_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 128, in create_district_daily
    data = data[['id', 'district_id', 'case_id', 'date', 'total']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['district_id'] not in index"
[2023-01-23 11:12:04,497] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=d_1_final_project, task_id=insert_district_daily, execution_date=20230123T082142, start_date=20230123T111203, end_date=20230123T111204
[2023-01-23 11:12:04,516] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task insert_district_daily ("['district_id'] not in index"; 6395)
[2023-01-23 11:12:04,532] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-23 11:12:04,579] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
